<?php
    echo "Geben Sie 3 Zahlen ein">
    echo "Wählen Sie eine der 5 Rechen Aufgaben"
    echo "1: Zahl1 + Zahl2 * Zahl3 = Ergebnis"
    echo "2: Zahl1 - Zahl2 / Zahl3 = Ergebnis"
    echo "3: Zahl1 * Zahl2 + Zahl3 = Ergebnis"
    echo "4: Zahl1 / Zahl2 * Zahl3 = Ergebnis"
    echo "5: Zahl1 + Zahl2 + Zahl3 = Ergebnis"

    $a = 10;
    $b = 5;

    $ergebnis = $a + $b;
    $ergebnis = $a - $b;
    $ergebnis = $a * $b;
    $ergebnis = $a / $b;

?> 